project:
  type: website

format:
  html:
    theme: cosmo
    fontsize: 1.1em
    linestretch: 2.0
    code-fold: true
    # embed-resources: true
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px
      gutter-width: 1.5rem

jupyter: python3