project:
  type: website
  output-dir: ../docs

website:
  title: "HP"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

permissions:
  contents: write
  pages: write
  id-token: write